#include <iostream>

using namespace std;

//Problem 2

//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.

int main()
{
	int a = 2;
	int aold = 1;
	int atemp;
	int total = 0;

	while (a<4000001){
		//cout << "a = " << a;
		if (a%2==0){
			total = total + a;
			//cout << " even.  Total = " << total;
		}
		//cout << endl;
		
		atemp = a;
		a = a + aold;
		aold = atemp;
	}

	cout << "Total = " << total << endl;
	return 0;
}
			
		
		
	